// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbPXi5W5WHUbrfaurZqiPKjceZko-RvUY',
    appId: '1:631612577209:web:05edc05ed4f8fd61765268',
    messagingSenderId: '631612577209',
    projectId: 'duseca-task-33f66',
    authDomain: 'duseca-task-33f66.firebaseapp.com',
    storageBucket: 'duseca-task-33f66.appspot.com',
    measurementId: 'G-07HK3L2DKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6cc6r82e6TCYA7csZKwSycmRTfObcijU',
    appId: '1:631612577209:android:9c1443602407ea81765268',
    messagingSenderId: '631612577209',
    projectId: 'duseca-task-33f66',
    storageBucket: 'duseca-task-33f66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_UYGN7tmxaWwx_-neXOL1GFvtRplBvWA',
    appId: '1:631612577209:ios:d1e95c6c62a28526765268',
    messagingSenderId: '631612577209',
    projectId: 'duseca-task-33f66',
    storageBucket: 'duseca-task-33f66.appspot.com',
    iosBundleId: 'com.example.dusecaFlutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbPXi5W5WHUbrfaurZqiPKjceZko-RvUY',
    appId: '1:631612577209:web:2bcc125d59f1c49b765268',
    messagingSenderId: '631612577209',
    projectId: 'duseca-task-33f66',
    authDomain: 'duseca-task-33f66.firebaseapp.com',
    storageBucket: 'duseca-task-33f66.appspot.com',
    measurementId: 'G-D2NPR634E0',
  );
}
